version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    REPO_FRONTEND: "ecommerce-frontend"
    REPO_BACKEND: "ecommerce-backend"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Frontend...
      - docker build -t $REPO_FRONTEND ./frontend
      - echo Building Backend...
      - docker build -t $REPO_BACKEND ./backend
  post_build:
    commands:
      - echo Pushing Docker images...
      - docker tag $REPO_FRONTEND:latest <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/$REPO_FRONTEND:latest
      - docker tag $REPO_BACKEND:latest <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/$REPO_BACKEND:latest
      - docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/$REPO_FRONTEND:latest
      - docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/$REPO_BACKEND:latest
artifacts:
  files:
    - '**/*'
